<a href="https://colab.research.google.com/github/chris-bhaila/PyTorch/blob/main/Intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np

# **LISTS**

In [8]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [10]:
np1 = np.random.rand(3,4)
np1

array([[0.17787579, 0.61113132, 0.42205518, 0.7836708 ],
       [0.51103409, 0.70802086, 0.19140783, 0.54815611],
       [0.04225148, 0.10852064, 0.87276234, 0.07209137]])

# **TENSORS**

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.3372, -0.6829, -0.2563, -0.6853],
        [-0.2971,  0.7278,  0.6987, -2.0659],
        [ 1.6883, -0.2758, -0.0489, -0.6246]])

In [13]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1779, 0.6111, 0.4221, 0.7837],
        [0.5110, 0.7080, 0.1914, 0.5482],
        [0.0423, 0.1085, 0.8728, 0.0721]], dtype=torch.float64)